name: KICS IaC Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
