name: KICS IaC Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: run KICS Scan
        uses: Checkmarx/kics-github-action@v1.4
        with:
          path: './deployments/terraform'
          output_path: results-dir
          platform_type: terraform
          output_formats: 'json,sarif,html'
          fail_on: high
          enable_comments: true
      - name: checkout sarif update action
        if: success() || failure()
        uses: actions/checkout@v2
        with:
          repository: koushik-goswami/update-sarif-action
          path: ./.github/actions/update-sarif-action
          ref: main
      - name: change permission
        if: success() || failure()
        run: |
          chmod +x ./.github/actions/update-sarif-action
          chmod +x ./results-dir/results.sarif
      - name: format sarif
        if: success() || failure()
        uses: ./.github/actions/update-sarif-action
        with:
          sarif_path: ./results-dir/results.sarif
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./results-dir/results.sarif
          category: my-analysis-tool
